// stet - A PostScript Interpreter
// Copyright (c) 2026 Scott Bowman
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Adobe CID ↔ Unicode mapping tables for CJK character collections.
//!
//! Covers the four Adobe CJK registry orderings (Japan1, CNS1, GB1,
//! Korea1). The PDF reader uses them to pick glyphs from a substitute font
//! when a CID font has no usable `/ToUnicode` CMap; text extraction uses
//! them to recover Unicode for CID-keyed fonts in both PDF and PostScript,
//! which is why they live here rather than in either interpreter.
//!
//! Two jobs, two answers — which is why there are two CID lookups:
//!
//! - [`cid_to_text`] is what the CID *means*: Adobe's
//!   `Adobe-<Ordering>-UCS2` CMap, the CID-to-Unicode mapping Acrobat
//!   extracts with. It covers every CID and may be several characters (a
//!   supplementary-plane character, a base plus a variation selector, a
//!   ligature). A vertical comma is `，`.
//! - [`cid_to_unicode`] is one code point whose glyph in a Unicode-keyed
//!   font *looks like* the CID's glyph. It comes from the
//!   `Uni<XX>-UTF32-H` CMaps, so a vertical comma is the presentation form
//!   U+FE10, which a substitute font draws vertically without layout
//!   features.
//!
//! [`unicode_to_cid`] reads the `Uni<XX>-UTF32-H` CMaps directly.
//!
//! The tables are generated by `scripts/gen_cid_unicode_tables.py`, which
//! documents the binary format. They are derived from Adobe's CMap
//! resources and carry Adobe's BSD-3-Clause notice, in
//! `LICENSE-ADOBE-CMAP` at the root of this crate.

use std::sync::OnceLock;

static JAPAN1: OnceLock<Tables> = OnceLock::new();
static CNS1: OnceLock<Tables> = OnceLock::new();
static GB1: OnceLock<Tables> = OnceLock::new();
static KOREA1: OnceLock<Tables> = OnceLock::new();

/// The decoded tables for one ordering.
#[derive(Default)]
struct Tables {
    /// UTF-8 text of every CID, concatenated.
    text: String,
    /// CID `n`'s text is `text[offsets[n]..offsets[n + 1]]`.
    offsets: Vec<u32>,
    /// `(code point, CID)` from `Uni<XX>-UTF32-H`, sorted by code point.
    to_cid: Vec<(u32, u16)>,
    /// Glyph-selection code point per CID; [`NO_CODE_POINT`] for none.
    glyph_code_point: Vec<u32>,
}

const NO_CODE_POINT: u32 = u32::MAX;

fn tables(ordering: &[u8]) -> Option<&'static Tables> {
    let (cell, data): (_, &[u8]) = match ordering {
        b"Japan1" => (&JAPAN1, include_bytes!("cid_japan1.bin")),
        b"CNS1" => (&CNS1, include_bytes!("cid_cns1.bin")),
        b"GB1" => (&GB1, include_bytes!("cid_gb1.bin")),
        b"Korea1" => (&KOREA1, include_bytes!("cid_korea1.bin")),
        _ => return None,
    };
    Some(cell.get_or_init(|| Tables::load(data).unwrap_or_default()))
}

/// The Unicode text Adobe assigns to `cid` in `ordering` (`b"Japan1"`,
/// `b"CNS1"`, `b"GB1"`, `b"Korea1"`), for text extraction.
///
/// `None` for an unknown ordering or a CID the collection does not define.
pub fn cid_to_text(ordering: &[u8], cid: u16) -> Option<&'static str> {
    tables(ordering)?.text(cid)
}

/// One code point for choosing `cid`'s glyph from a Unicode-keyed
/// substitute font.
///
/// A CID that `Uni<XX>-UTF32-H` reaches maps to a code point that selects
/// it there. When several do — Japan1 CID 3284 is reached from both 日
/// U+65E5 and the Kangxi radical ⽇ U+2F47 — the one [`cid_to_text`] gives
/// wins; failing that, one outside the Private Use Area, then one that is
/// not a radical, then the lowest.
///
/// A CID no Unicode encoding reaches — a half-width, proportional, or
/// other variant of a character that has its own CID — maps to the
/// character it is a variant of, when [`cid_to_text`] gives exactly one
/// (a trailing variation selector aside). A CID whose text is a sequence
/// maps to nothing.
pub fn cid_to_unicode(ordering: &[u8], cid: u16) -> Option<u32> {
    let cp = *tables(ordering)?.glyph_code_point.get(cid as usize)?;
    (cp != NO_CODE_POINT).then_some(cp)
}

/// Look up Unicode → CID for a given Adobe CID registry/ordering.
/// Used for UCS2-based CMap encodings (e.g. UniJIS-UCS2-H) where
/// character codes are Unicode values that need mapping to CIDs.
pub fn unicode_to_cid(ordering: &[u8], unicode: u32) -> Option<u16> {
    let to_cid = &tables(ordering)?.to_cid;
    let i = to_cid.binary_search_by_key(&unicode, |&(cp, _)| cp).ok()?;
    Some(to_cid[i].1)
}

impl Tables {
    fn text(&self, cid: u16) -> Option<&str> {
        let i = cid as usize;
        let (&start, &end) = (self.offsets.get(i)?, self.offsets.get(i + 1)?);
        let text = &self.text[start as usize..end as usize];
        (!text.is_empty()).then_some(text)
    }

    /// Decode a table in the format `gen_cid_unicode_tables.py` writes.
    /// `None` on any inconsistency: a corrupt table maps nothing rather
    /// than mapping wrongly.
    fn load(compressed: &[u8]) -> Option<Tables> {
        use flate2::read::ZlibDecoder;
        use std::io::Read;

        let mut raw = Vec::new();
        ZlibDecoder::new(compressed).read_to_end(&mut raw).ok()?;
        let mut r = Reader(&raw);
        if r.take(5)? != b"CIDU\x01" {
            return None;
        }

        let n_cids = r.u32()? as usize;
        let mut text = String::new();
        let mut offsets = Vec::with_capacity(n_cids + 1);
        offsets.push(0);
        for _ in 0..n_cids {
            let len = r.take(1)?[0] as usize;
            text.push_str(std::str::from_utf8(r.take(len)?).ok()?);
            offsets.push(u32::try_from(text.len()).ok()?);
        }

        let n_pairs = r.u32()? as usize;
        let mut to_cid = Vec::with_capacity(n_pairs);
        for _ in 0..n_pairs {
            let cp = r.u32()?;
            let cid = u16::from_le_bytes(r.take(2)?.try_into().ok()?);
            to_cid.push((cp, cid));
        }
        if !r.0.is_empty() || !to_cid.is_sorted_by_key(|&(cp, _)| cp) {
            return None;
        }

        let mut tables = Tables {
            text,
            offsets,
            to_cid,
            glyph_code_point: Vec::new(),
        };
        tables.glyph_code_point = tables.glyph_code_points(n_cids);
        Some(tables)
    }

    /// Choose each CID's glyph-selection code point; see [`cid_to_unicode`].
    fn glyph_code_points(&self, n_cids: usize) -> Vec<u32> {
        let mut chosen = vec![NO_CODE_POINT; n_cids];
        let canonical = |cid: u16| self.text(cid).and_then(|t| t.chars().next());
        for &(cp, cid) in &self.to_cid {
            let Some(slot) = chosen.get_mut(cid as usize) else {
                continue;
            };
            let first = canonical(cid).map(u32::from);
            let rank = |cp: u32| (Some(cp) != first, is_private_use(cp), is_radical(cp), cp);
            if *slot == NO_CODE_POINT || rank(cp) < rank(*slot) {
                *slot = cp;
            }
        }
        for (cid, slot) in chosen.iter_mut().enumerate() {
            if *slot == NO_CODE_POINT
                && let Some(text) = self.text(cid as u16)
                && let Some(base) = single_character(text)
            {
                *slot = base as u32;
            }
        }
        chosen
    }
}

/// `text`'s character if it is one, optionally followed by variation
/// selectors, which pick a glyph variant of that same character.
fn single_character(text: &str) -> Option<char> {
    let mut chars = text.chars();
    let base = chars.next()?;
    chars.all(is_variation_selector).then_some(base)
}

fn is_variation_selector(c: char) -> bool {
    matches!(c, '\u{FE00}'..='\u{FE0F}' | '\u{E0100}'..='\u{E01EF}')
}

fn is_private_use(cp: u32) -> bool {
    matches!(cp, 0xE000..=0xF8FF | 0xF0000..=0xFFFFD | 0x100000..=0x10FFFD)
}

/// CJK Radicals Supplement (U+2E80–2EFF) and Kangxi Radicals
/// (U+2F00–2FDF), which are adjacent: code points for a radical as a
/// component, which Adobe maps to the same CID as the ideograph.
fn is_radical(cp: u32) -> bool {
    (0x2E80..=0x2FDF).contains(&cp)
}

/// A cursor over the decompressed table.
struct Reader<'a>(&'a [u8]);

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Option<&'a [u8]> {
        if self.0.len() < n {
            return None;
        }
        let (head, tail) = self.0.split_at(n);
        self.0 = tail;
        Some(head)
    }

    fn u32(&mut self) -> Option<u32> {
        Some(u32::from_le_bytes(self.take(4)?.try_into().ok()?))
    }
}

/// How a predefined `Uni…` CMap spells Unicode in its character codes: a
/// composite font using one shows text whose codes are the text itself.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum UnicodeCMap {
    /// `Uni…-UCS2-…` and `Uni…-UTF16-…`: UTF-16 code units, a surrogate
    /// pair forming one four-byte code.
    Utf16,
    /// `Uni…-UTF32-…`: the code is the scalar value.
    Utf32,
    /// `Uni…-UTF8-…`: the code's bytes are UTF-8.
    Utf8,
}

impl UnicodeCMap {
    /// The encoding of the predefined CMap `name` (`UniJIS-UCS2-H`,
    /// `UniGB-UTF16-V`, …), or `None` when its codes are not Unicode.
    pub fn from_cmap_name(name: &[u8]) -> Option<Self> {
        if !name.starts_with(b"Uni") {
            return None;
        }
        let has = |needle: &[u8]| name.windows(needle.len()).any(|w| w == needle);
        if has(b"-UCS2-") || has(b"-UTF16-") {
            Some(Self::Utf16)
        } else if has(b"-UTF32-") {
            Some(Self::Utf32)
        } else if has(b"-UTF8-") {
            Some(Self::Utf8)
        } else {
            None
        }
    }

    /// The character `code` spells, or `None` when it spells no valid
    /// one — or a control character, which is not text.
    pub fn code_to_char(self, code: u32) -> Option<char> {
        let ch = match self {
            Self::Utf16 if code > 0xFFFF => {
                let (hi, lo) = ((code >> 16) as u16, code as u16);
                char::decode_utf16([hi, lo]).next()?.ok()?
            }
            Self::Utf16 | Self::Utf32 => char::from_u32(code)?,
            Self::Utf8 => {
                let bytes = code.to_be_bytes();
                let start = bytes.iter().position(|&b| b != 0).unwrap_or(3);
                std::str::from_utf8(&bytes[start..]).ok()?.chars().next()?
            }
        };
        (!ch.is_control()).then_some(ch)
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn unicode_cmap_names() {
        use UnicodeCMap::*;
        assert_eq!(UnicodeCMap::from_cmap_name(b"UniJIS-UCS2-H"), Some(Utf16));
        assert_eq!(UnicodeCMap::from_cmap_name(b"UniGB-UTF16-V"), Some(Utf16));
        assert_eq!(UnicodeCMap::from_cmap_name(b"UniKS-UTF32-H"), Some(Utf32));
        assert_eq!(UnicodeCMap::from_cmap_name(b"UniCNS-UTF8-H"), Some(Utf8));
        assert_eq!(
            UnicodeCMap::from_cmap_name(b"UniJIS-UCS2-HW-H"),
            Some(Utf16)
        );
        assert_eq!(UnicodeCMap::from_cmap_name(b"90ms-RKSJ-H"), None);
        assert_eq!(UnicodeCMap::from_cmap_name(b"Identity-H"), None);
    }

    #[test]
    fn unicode_cmap_codes() {
        use UnicodeCMap::*;
        assert_eq!(Utf16.code_to_char(0x65E5), Some('日'));
        // U+20BB7 as a surrogate pair.
        assert_eq!(Utf16.code_to_char(0xD842_DFB7), Some('𠮷'));
        assert_eq!(Utf16.code_to_char(0xD842), None);
        assert_eq!(Utf32.code_to_char(0x20BB7), Some('𠮷'));
        assert_eq!(Utf8.code_to_char(0xE6_97_A5), Some('日'));
        assert_eq!(Utf8.code_to_char(0x41), Some('A'));
        assert_eq!(Utf8.code_to_char(0xFF), None);
        assert_eq!(Utf32.code_to_char(0x07), None);
    }

    use super::*;

    const ORDERINGS: [&[u8]; 4] = [b"Japan1", b"CNS1", b"GB1", b"Korea1"];

    #[test]
    fn unknown_ordering_maps_nothing() {
        assert_eq!(cid_to_text(b"Identity", 34), None);
        assert_eq!(cid_to_unicode(b"Identity", 34), None);
        assert_eq!(unicode_to_cid(b"Identity", 0x41), None);
    }

    #[test]
    fn every_table_loads() {
        for ordering in ORDERINGS {
            let t = tables(ordering).unwrap();
            assert!(t.offsets.len() > 18_000, "{ordering:?}");
            assert!(t.to_cid.len() > 15_000, "{ordering:?}");
            // CID 34 is 'A' in each Adobe CJK collection, both ways.
            assert_eq!(cid_to_text(ordering, 34), Some("A"), "{ordering:?}");
            assert_eq!(cid_to_unicode(ordering, 34), Some(0x41), "{ordering:?}");
            assert_eq!(unicode_to_cid(ordering, 0x41), Some(34), "{ordering:?}");
            // CID 0 is .notdef, and CIDs past the collection map nothing.
            assert_eq!(cid_to_text(ordering, 0), None);
            assert_eq!(cid_to_unicode(ordering, 0), None);
            assert_eq!(cid_to_text(ordering, u16::MAX), None);
            assert_eq!(cid_to_unicode(ordering, u16::MAX), None);
        }
    }

    #[test]
    fn cid_one_is_a_space_not_a_no_break_space() {
        // Uni*-UTF32-H reaches CID 1 from both U+0020 and U+00A0.
        for ordering in ORDERINGS {
            assert_eq!(cid_to_text(ordering, 1), Some(" "), "{ordering:?}");
            assert_eq!(cid_to_unicode(ordering, 1), Some(0x20), "{ordering:?}");
        }
    }

    #[test]
    fn ideograph_wins_over_the_radical_sharing_its_cid() {
        // Japan1 CID 3284 is reached from 日 U+65E5 and ⽇ U+2F47.
        assert_eq!(cid_to_text(b"Japan1", 3284), Some("日"));
        assert_eq!(cid_to_unicode(b"Japan1", 3284), Some(0x65E5));
        assert_eq!(unicode_to_cid(b"Japan1", 0x65E5), Some(3284));
        assert_eq!(unicode_to_cid(b"Japan1", 0x2F47), Some(3284));
    }

    #[test]
    fn vertical_forms_differ_between_text_and_glyph_selection() {
        // GB1 CID 574 is the vertical ideographic full stop: its text is
        // 。, and its glyph is the presentation form U+FE12 (not the
        // Private Use code point U+E78E that also reaches it).
        assert_eq!(cid_to_text(b"GB1", 574), Some("。"));
        assert_eq!(cid_to_unicode(b"GB1", 574), Some(0xFE12));
    }

    #[test]
    fn variants_no_encoding_reaches_fall_back_to_their_character() {
        // Half-width Latin: nothing encodes these CIDs, since Unicode 'A'
        // selects the proportional CID.
        assert_eq!(cid_to_text(b"Japan1", 232), Some("!"));
        assert_eq!(cid_to_unicode(b"Japan1", 232), Some(0x21));
        assert_eq!(cid_to_unicode(b"GB1", 815), Some(0x22));
        assert_eq!(unicode_to_cid(b"Japan1", 0x21), Some(2));
    }

    #[test]
    fn supplementary_plane_characters_survive() {
        // Japan1 CID 13706 is 𠮷 U+20BB7.
        assert_eq!(cid_to_text(b"Japan1", 13706), Some("\u{20BB7}"));
        assert_eq!(cid_to_unicode(b"Japan1", 13706), Some(0x20BB7));
        assert_eq!(unicode_to_cid(b"Japan1", 0x20BB7), Some(13706));
    }

    #[test]
    fn variation_sequences_keep_their_selector_in_text_only() {
        // Japan1 CID 1383 is 牙 with an ideographic variation selector.
        assert_eq!(cid_to_text(b"Japan1", 1383), Some("\u{7259}\u{E0100}"));
        assert_eq!(cid_to_unicode(b"Japan1", 1383), Some(0x7259));
    }

    #[test]
    fn adobe_no_unicode_markers_map_nothing() {
        // Adobe-CNS1-UCS2 gives these U+FFFD; Adobe-Korea1-UCS2 gives CID
        // 8752 the control character U+0016.
        assert_eq!(cid_to_text(b"CNS1", 124), None);
        assert_eq!(cid_to_unicode(b"CNS1", 124), None);
        assert_eq!(cid_to_text(b"Korea1", 8752), None);
    }

    #[test]
    fn corrupt_tables_load_as_nothing() {
        let good = include_bytes!("cid_korea1.bin");
        assert!(Tables::load(good).is_some());
        assert!(Tables::load(&good[..good.len() / 2]).is_none());
        assert!(Tables::load(b"").is_none());
    }

    #[test]
    fn single_character_allows_trailing_variation_selectors() {
        assert_eq!(single_character("a"), Some('a'));
        assert_eq!(single_character("\u{722B}\u{FE00}"), Some('\u{722B}'));
        assert_eq!(single_character("ab"), None);
        assert_eq!(single_character(""), None);
    }
}
