// stet - A PostScript Interpreter
// Copyright (c) 2026 Scott Bowman
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! The CLI's colour-management options reach every conversion of a
//! PostScript page, including those made while rendering it.
//!
//! The interpreter converts a CMYK fill when it is painted, but a DeviceCMYK
//! image is converted when the page is rendered, by a colour cache the PNG
//! device builds for itself. That cache was once built with default options,
//! so `--bpc off` changed fills and left images as they were.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Path to the `stet` binary built alongside this test.
fn stet_bin() -> PathBuf {
    // target/<profile>/deps/<test> → target/<profile>/stet
    let mut p = std::env::current_exe().expect("test exe path");
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join(if cfg!(windows) { "stet.exe" } else { "stet" })
}

/// A CMYK profile whose colorimetric black is L*=8, far enough from sRGB's
/// black for black-point compensation to show. Generated by
/// `stet-graphics/tests/data/cmyk_intent/generate.py`.
fn profile() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../stet-graphics/tests/data/cmyk_intent/split.icc")
}

/// A scratch directory that cleans itself up.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> Self {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "stet-icc-options-{}-{}-{:?}",
            tag,
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).expect("create temp dir");
        Self(p)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// A 20×10 pt page: the left half filled with `cmyk`, the right half a
/// 1×1 DeviceCMYK image of the same colour.
fn fill_beside_image(cmyk: [u8; 4]) -> String {
    let [c, m, y, k] = cmyk.map(|v| v as f64 / 255.0);
    let hex: String = cmyk.iter().map(|v| format!("{v:02X}")).collect();
    format!(
        "%!PS\n\
         << /PageSize [20 10] >> setpagedevice\n\
         {c} {m} {y} {k} setcmykcolor 0 0 10 10 rectfill\n\
         gsave 10 0 translate 10 10 scale /DeviceCMYK setcolorspace\n\
         << /ImageType 1 /Width 1 /Height 1 /BitsPerComponent 8\n\
            /Decode [0 1 0 1 0 1 0 1] /ImageMatrix [1 0 0 -1 0 1]\n\
            /DataSource <{hex}> >> image\n\
         grestore showpage\n"
    )
}

/// Render `ps` to PNG at 72 dpi with `args`; returns the RGB of the pixel at
/// the centre of the left half and of the right half.
fn render(ps: &str, args: &[&str], tag: &str) -> ([u8; 3], [u8; 3]) {
    let dir = TempDir::new(tag);
    std::fs::write(dir.0.join("in.ps"), ps).expect("write ps");
    let out = Command::new(stet_bin())
        .current_dir(&dir.0)
        .args(["--device", "png", "--dpi", "72", "-o", "out.png"])
        .args(args)
        .arg("in.ps")
        .output()
        .expect("run stet");
    assert!(
        out.status.success(),
        "stet failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let file = std::fs::File::open(dir.0.join("out.png")).expect("open png");
    let mut reader = png::Decoder::new(std::io::BufReader::new(file))
        .read_info()
        .expect("png header");
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("png frame");
    let channels = info.color_type.samples();
    let pixel = |x: usize, y: usize| {
        let at = (y * info.width as usize + x) * channels;
        [buf[at], buf[at + 1], buf[at + 2]]
    };
    (pixel(5, 5), pixel(15, 5))
}

#[test]
fn bpc_reaches_postscript_images() {
    let profile = profile();
    let profile = profile.to_str().expect("utf-8 path");
    let ps = fill_beside_image([0, 0, 0, 255]);
    let mut seen = Vec::new();
    for bpc in ["on", "off"] {
        let (fill, image) = render(
            &ps,
            &["--cmyk-profile", profile, "--bpc", bpc],
            &format!("bpc-{bpc}"),
        );
        assert_eq!(fill, image, "--bpc {bpc}: fill {fill:?}, image {image:?}");
        seen.push(fill);
    }
    assert_ne!(seen[0], seen[1], "--bpc made no difference to the black");
}
