// stet - A PostScript Interpreter
// Copyright (c) 2026 Scott Bowman
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! The CLI's colour-management options reach every conversion of a
//! PostScript page, including those made while rendering it.
//!
//! The interpreter converts a CMYK fill when it is painted, but a DeviceCMYK
//! image is converted when the page is rendered, by a colour cache the PNG
//! device builds for itself. That cache was once built with default options,
//! so `--bpc off` changed fills and left images as they were.
//!
//! `--default-intent` sets the rendering intent pages start with, for
//! PostScript and PDF input alike.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Path to the `stet` binary built alongside this test.
fn stet_bin() -> PathBuf {
    // target/<profile>/deps/<test> → target/<profile>/stet
    let mut p = std::env::current_exe().expect("test exe path");
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join(if cfg!(windows) { "stet.exe" } else { "stet" })
}

/// A CMYK profile whose colorimetric black is L*=8, far enough from sRGB's
/// black for black-point compensation to show. Generated by
/// `stet-graphics/tests/data/cmyk_intent/generate.py`.
fn profile() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../stet-graphics/tests/data/cmyk_intent/split.icc")
}

/// A scratch directory that cleans itself up.
struct TempDir(PathBuf);

impl TempDir {
    fn new(tag: &str) -> Self {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "stet-icc-options-{}-{}-{:?}",
            tag,
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).expect("create temp dir");
        Self(p)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// A 20×10 pt page: the left half filled with `cmyk`, the right half a
/// 1×1 DeviceCMYK image of the same colour, after `prefix`.
fn fill_beside_image(prefix: &str, cmyk: [u8; 4]) -> String {
    let [c, m, y, k] = cmyk.map(|v| v as f64 / 255.0);
    let hex: String = cmyk.iter().map(|v| format!("{v:02X}")).collect();
    format!(
        "%!PS\n\
         << /PageSize [20 10] >> setpagedevice\n\
         {prefix}\n\
         {c} {m} {y} {k} setcmykcolor 0 0 10 10 rectfill\n\
         gsave 10 0 translate 10 10 scale /DeviceCMYK setcolorspace\n\
         << /ImageType 1 /Width 1 /Height 1 /BitsPerComponent 8\n\
            /Decode [0 1 0 1 0 1 0 1] /ImageMatrix [1 0 0 -1 0 1]\n\
            /DataSource <{hex}> >> image\n\
         grestore showpage\n"
    )
}

/// The same page as [`fill_beside_image`], as a PDF, with `prefix` at the
/// start of its content stream.
fn pdf_fill_beside_image(prefix: &str, cmyk: [u8; 4]) -> Vec<u8> {
    let [c, m, y, k] = cmyk.map(|v| v as f64 / 255.0);
    let mut content = format!(
        "{prefix} {c} {m} {y} {k} k 0 0 10 10 re f\n\
         q 10 0 0 10 10 0 cm BI /W 1 /H 1 /CS /DeviceCMYK /BPC 8 ID "
    )
    .into_bytes();
    content.extend(cmyk);
    content.extend(b"\nEI Q\n");
    let mut stream = format!("<< /Length {} >>\nstream\n", content.len()).into_bytes();
    stream.extend(&content);
    stream.extend(b"\nendstream");
    let objects: [Vec<u8>; 4] = [
        b"<< /Type /Catalog /Pages 2 0 R >>".to_vec(),
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>".to_vec(),
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 20 10] /Contents 4 0 R \
          /Resources << >> >>"
            .to_vec(),
        stream,
    ];
    let mut pdf = b"%PDF-1.7\n".to_vec();
    let mut offsets = Vec::new();
    for (i, body) in objects.iter().enumerate() {
        offsets.push(pdf.len());
        pdf.extend(format!("{} 0 obj\n", i + 1).as_bytes());
        pdf.extend(body);
        pdf.extend(b"\nendobj\n");
    }
    let xref = pdf.len();
    pdf.extend(format!("xref\n0 {}\n0000000000 65535 f\r\n", objects.len() + 1).as_bytes());
    for off in offsets {
        pdf.extend(format!("{off:010} 00000 n\r\n").as_bytes());
    }
    pdf.extend(
        format!(
            "trailer\n<< /Size {} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n",
            objects.len() + 1
        )
        .as_bytes(),
    );
    pdf
}

/// Run stet on `input` (written as `in.<ext>`) with `args`; returns its exit
/// status and output.
fn run(input: &[u8], ext: &str, args: &[&str], dir: &TempDir) -> std::process::Output {
    let name = format!("in.{ext}");
    std::fs::write(dir.0.join(&name), input).expect("write input");
    Command::new(stet_bin())
        .current_dir(&dir.0)
        .args(["--device", "png", "--dpi", "72", "-o", "out.png"])
        .args(args)
        .arg(&name)
        .output()
        .expect("run stet")
}

/// Render `ps` to PNG at 72 dpi with `args`; returns the RGB of the pixel at
/// the centre of the left half and of the right half.
fn render(ps: &str, args: &[&str], tag: &str) -> ([u8; 3], [u8; 3]) {
    render_input(ps.as_bytes(), "ps", args, tag)
}

/// [`render`] for any input: `ext` is `ps` or `pdf`.
fn render_input(input: &[u8], ext: &str, args: &[&str], tag: &str) -> ([u8; 3], [u8; 3]) {
    let dir = TempDir::new(tag);
    let out = run(input, ext, args, &dir);
    assert!(
        out.status.success(),
        "stet failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );

    let file = std::fs::File::open(dir.0.join("out.png")).expect("open png");
    let mut reader = png::Decoder::new(std::io::BufReader::new(file))
        .read_info()
        .expect("png header");
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("png frame");
    let channels = info.color_type.samples();
    let pixel = |x: usize, y: usize| {
        let at = (y * info.width as usize + x) * channels;
        [buf[at], buf[at + 1], buf[at + 2]]
    };
    (pixel(5, 5), pixel(15, 5))
}

#[test]
fn bpc_reaches_postscript_images() {
    let profile = profile();
    let profile = profile.to_str().expect("utf-8 path");
    let ps = fill_beside_image("", [0, 0, 0, 255]);
    let mut seen = Vec::new();
    for bpc in ["on", "off"] {
        let (fill, image) = render(
            &ps,
            &["--cmyk-profile", profile, "--bpc", bpc],
            &format!("bpc-{bpc}"),
        );
        assert_eq!(fill, image, "--bpc {bpc}: fill {fill:?}, image {image:?}");
        seen.push(fill);
    }
    assert_ne!(seen[0], seen[1], "--bpc made no difference to the black");
}

/// A page of [`fill_beside_image`] in `ext` (`ps` or `pdf`) that first
/// selects `intent`, or nothing when it is `None`.
fn page(ext: &str, intent: Option<&str>, cmyk: [u8; 4]) -> Vec<u8> {
    match (ext, intent) {
        ("ps", None) => fill_beside_image("", cmyk).into_bytes(),
        ("ps", Some(i)) => {
            fill_beside_image(&format!("/{i} setrenderingintent"), cmyk).into_bytes()
        }
        (_, None) => pdf_fill_beside_image("", cmyk),
        (_, Some(i)) => pdf_fill_beside_image(&format!("/{i} ri"), cmyk),
    }
}

/// `--default-intent` is where PostScript and PDF pages start: the same as
/// selecting the intent in the file, fills and images alike, and the file's
/// own choice still wins.
#[test]
fn default_intent_is_where_pages_start() {
    let profile = profile();
    let profile = profile.to_str().expect("utf-8 path");
    let black = [0, 0, 0, 255];
    let flag = ["--cmyk-profile", profile, "--default-intent", "perceptual"];
    let plain = ["--cmyk-profile", profile];
    for ext in ["ps", "pdf"] {
        let render = |intent, args: &[&str], tag: &str| {
            render_input(
                &page(ext, intent, black),
                ext,
                args,
                &format!("{ext}-{tag}"),
            )
        };
        let asked = render(Some("Perceptual"), &plain, "asked");
        let relative = render(None, &plain, "relative");
        let default = render(None, &flag, "default");
        let overridden = render(Some("RelativeColorimetric"), &flag, "overridden");
        assert_ne!(asked, relative, "{ext}: the intents must differ");
        assert_eq!(asked.0, asked.1, "{ext}: fill and image");
        assert_eq!(default, asked, "{ext}: --default-intent perceptual");
        assert_eq!(overridden, relative, "{ext}: the file's own intent wins");
    }
}

#[test]
fn default_intent_values_are_checked() {
    let dir = TempDir::new("intent-refused");
    let ps = fill_beside_image("", [0, 0, 0, 255]);
    for (args, message) in [
        (&["--default-intent", "vivid"][..], "must be one of"),
        (
            &["--no-icc", "--default-intent", "perceptual"][..],
            "cannot be combined with --no-icc",
        ),
    ] {
        let out = run(ps.as_bytes(), "ps", args, &dir);
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(!out.status.success(), "{args:?} accepted");
        assert!(stderr.contains(message), "{args:?}: {stderr}");
    }
}
