// Integration tests: parse real PDF files generated by stet.

use stet_pdf_reader::PdfDocument;

fn load_pdf(name: &str) -> Vec<u8> {
    let path = format!(
        "{}/samples/{name}",
        env!("CARGO_MANIFEST_DIR").replace("/crates/stet-pdf-reader", "")
    );
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read {path}: {e}"))
}

fn load_pdf_abs(path: &str) -> Option<Vec<u8>> {
    std::fs::read(path).ok()
}

#[test]
fn parse_hospital_pdf() {
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    assert_eq!(doc.page_count(), 1);

    let (w, h) = doc.page_size(0).unwrap();
    // EPS — dimensions vary, just check they're reasonable
    assert!(w > 100.0 && w < 2000.0, "width = {w}");
    assert!(h > 100.0 && h < 2000.0, "height = {h}");

    // Should have content
    let contents = doc.page_contents(0).unwrap();
    assert!(!contents.is_empty(), "page should have content stream");
}

#[test]
fn parse_javaplatform_pdf() {
    let data = load_pdf("javaplatform.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    assert_eq!(doc.page_count(), 25);

    let (w, h) = doc.page_size(0).unwrap();
    assert!((w - 612.0).abs() < 1.0, "width = {w}");
    assert!((h - 792.0).abs() < 1.0, "height = {h}");

    // Check all pages have content
    for i in 0..25 {
        let contents = doc.page_contents(i).unwrap();
        assert!(!contents.is_empty(), "page {i} should have content");
    }
}

#[test]
fn parse_other_sample_pdfs() {
    // Test the other sample PDFs we have
    for name in &["10-ch8.pdf", "14-ch12.pdf", "16-ch14.pdf"] {
        let data = load_pdf(name);
        let doc = PdfDocument::from_bytes(&data).unwrap_or_else(|e| {
            panic!("failed to parse {name}: {e}");
        });
        assert!(doc.page_count() > 0, "{name} should have pages");

        let (w, h) = doc.page_size(0).unwrap();
        assert!(w > 0.0 && h > 0.0, "{name}: invalid page size {w}x{h}");
    }
}

/// Test against external PDFs if available (e.g., downloaded or from /tmp).
#[test]
fn parse_external_pdfs() {
    // Try any PDFs in /tmp
    let paths: Vec<_> = std::fs::read_dir("/tmp")
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "pdf"))
        .map(|e| e.path())
        .collect();

    let mut parsed = 0;
    let mut failed = 0;
    for path in &paths {
        if let Some(data) = load_pdf_abs(path.to_str().unwrap()) {
            match PdfDocument::from_bytes(&data) {
                Ok(doc) => {
                    assert!(doc.page_count() > 0 || doc.page_count() == 0);
                    parsed += 1;
                }
                Err(stet_pdf_reader::PdfError::Encrypted) => {
                    parsed += 1; // Expected failure for encrypted PDFs
                }
                Err(_e) => {
                    failed += 1;
                    eprintln!("  FAIL: {}: {_e}", path.display());
                }
            }
        }
    }
    if !paths.is_empty() {
        eprintln!("External PDFs: {parsed} parsed, {failed} failed out of {} total", paths.len());
    }
}
