// Integration tests: parse real PDF files generated by stet.

use stet_pdf_reader::PdfDocument;

fn load_pdf(name: &str) -> Vec<u8> {
    let path = format!(
        "{}/samples/{name}",
        env!("CARGO_MANIFEST_DIR").replace("/crates/stet-pdf-reader", "")
    );
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read {path}: {e}"))
}

fn load_pdf_abs(path: &str) -> Option<Vec<u8>> {
    std::fs::read(path).ok()
}

#[test]
fn parse_hospital_pdf() {
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    assert_eq!(doc.page_count(), 1);

    let (w, h) = doc.page_size(0).unwrap();
    // EPS — dimensions vary, just check they're reasonable
    assert!(w > 100.0 && w < 2000.0, "width = {w}");
    assert!(h > 100.0 && h < 2000.0, "height = {h}");

    // Should have content
    let contents = doc.page_contents(0).unwrap();
    assert!(!contents.is_empty(), "page should have content stream");
}

#[test]
fn parse_javaplatform_pdf() {
    let data = load_pdf("javaplatform.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    assert_eq!(doc.page_count(), 25);

    let (w, h) = doc.page_size(0).unwrap();
    assert!((w - 612.0).abs() < 1.0, "width = {w}");
    assert!((h - 792.0).abs() < 1.0, "height = {h}");

    // Check all pages have content
    for i in 0..25 {
        let contents = doc.page_contents(i).unwrap();
        assert!(!contents.is_empty(), "page {i} should have content");
    }
}

#[test]
fn parse_other_sample_pdfs() {
    // Test the other sample PDFs we have (skip if not present)
    for name in &["10-ch8.pdf", "ppst32.pdf"] {
        let path = format!(
            "{}/samples/{name}",
            env!("CARGO_MANIFEST_DIR").replace("/crates/stet-pdf-reader", "")
        );
        let Some(data) = load_pdf_abs(&path) else {
            eprintln!("Skipping {name} — not found");
            continue;
        };
        let doc = PdfDocument::from_bytes(&data).unwrap_or_else(|e| {
            panic!("failed to parse {name}: {e}");
        });
        assert!(doc.page_count() > 0, "{name} should have pages");

        let (w, h) = doc.page_size(0).unwrap();
        assert!(w > 0.0 && h > 0.0, "{name}: invalid page size {w}x{h}");
    }
}

#[test]
fn render_hospital_pdf() {
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();

    // Render page 0 at 72 DPI to get a display list
    let display_list = doc.render_page(0, 72.0).unwrap();
    assert!(!display_list.is_empty(), "display list should not be empty");
    eprintln!("hospital.pdf: {} display elements", display_list.len());
}

#[test]
fn render_hospital_pdf_to_rgba() {
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();

    // Render to pixels at 72 DPI
    let (rgba, w, h) = doc.render_page_to_rgba(0, 72.0).unwrap();
    assert!(w > 0 && h > 0, "pixel dimensions should be positive");
    assert_eq!(rgba.len(), (w * h * 4) as usize, "RGBA data size mismatch");

    // Check that not all pixels are the same (something was drawn)
    let all_white = rgba
        .chunks(4)
        .all(|p| p[0] == 255 && p[1] == 255 && p[2] == 255);
    // Note: with no text rendering yet, the page might be mostly white,
    // but hospital.pdf has graphics that should produce non-white pixels
    eprintln!("hospital.pdf render: {w}x{h}, all_white={all_white}");
}

#[test]
fn render_javaplatform_pages() {
    let data = load_pdf("javaplatform.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();

    // Render first 3 pages at low DPI
    for page in 0..3.min(doc.page_count()) {
        let result = doc.render_page(page, 72.0);
        match result {
            Ok(dl) => eprintln!("javaplatform.pdf page {page}: {} elements", dl.len()),
            Err(e) => eprintln!("javaplatform.pdf page {page}: error: {e}"),
        }
    }
}

#[test]
fn render_hospital_pdf_to_png() {
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();

    let (rgba, w, h) = doc.render_page_to_rgba(0, 150.0).unwrap();

    let out_path = format!(
        "{}/samples/hospital-pdf-render.png",
        env!("CARGO_MANIFEST_DIR").replace("/crates/stet-pdf-reader", "")
    );
    write_png(&out_path, &rgba, w, h);
    eprintln!("Wrote {out_path} ({w}x{h})");
}

#[test]
fn render_javaplatform_page1_to_png() {
    let data = load_pdf("javaplatform.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();

    let (rgba, w, h) = doc.render_page_to_rgba(0, 150.0).unwrap();

    let out_path = format!(
        "{}/samples/javaplatform-p1-pdf-render.png",
        env!("CARGO_MANIFEST_DIR").replace("/crates/stet-pdf-reader", "")
    );
    write_png(&out_path, &rgba, w, h);
    eprintln!("Wrote {out_path} ({w}x{h})");
}

fn write_png(path: &str, rgba: &[u8], width: u32, height: u32) {
    let file = std::fs::File::create(path).unwrap();
    let w = std::io::BufWriter::new(file);
    let mut encoder = png::Encoder::new(w, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    let mut writer = encoder.write_header().unwrap();
    writer.write_image_data(rgba).unwrap();
}

#[test]
fn diagnose_coordinate_system() {
    use stet_graphics::display_list::DisplayElement;

    // DIAGNOSIS: The initial CTM in render_page() Y-flips [scale, 0, 0, -scale, 0, ury*scale].
    // But hospital.pdf and javaplatform.pdf content streams both start with a cm that
    // also Y-flips: "0.24 0 0 -0.24 0 690.24 cm". The two flips cancel, giving a combined
    // CTM of [0.24, 0, 0, 0.24, 0, 0] — no flip, no offset. This means content meant
    // for the top of the page (low y' in post-cm space) ends up at high device Y (bottom
    // of pixmap). The page content is rendered upside-down.
    //
    // FIX: Remove the Y-flip from render_page()'s initial CTM. Use
    //   [scale, 0, 0, scale, -llx*scale, -lly*scale]
    // instead of
    //   [scale, 0, 0, -scale, -llx*scale, ury*scale]
    // The content stream's own cm handles the Y-flip internally.

    // === hospital.pdf ===
    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    let info = doc.page_info(0).unwrap();
    eprintln!("=== hospital.pdf page 0 ===");
    eprintln!("  MediaBox: {:?}", info.media_box);
    eprintln!("  CropBox:  {:?}", info.crop_box);
    eprintln!("  Rotate:   {}", info.rotate);
    let (w, h) = doc.page_size(0).unwrap();
    eprintln!("  page_size: {w} x {h} points");

    // Show first 500 bytes of content stream
    let contents = doc.page_contents(0).unwrap();
    let preview_len = 500.min(contents.len());
    let preview = String::from_utf8_lossy(&contents[..preview_len]);
    eprintln!("  Content stream first {preview_len} bytes:\n---\n{preview}\n---");

    // Render at 72 DPI (1:1 scale) so device coords = point coords
    let display_list = doc.render_page(0, 72.0).unwrap();
    eprintln!("  Display list: {} elements", display_list.len());

    // Compute expected CTM for 72 DPI, no rotation
    let [llx, lly, urx, ury] = info.crop_box;
    let scale = 72.0 / 72.0; // = 1.0
    eprintln!(
        "  Expected CTM: [{scale}, 0, 0, {}, {}, {}]",
        -scale,
        -llx * scale,
        ury * scale
    );
    eprintln!(
        "  => PDF point (0, 0) maps to device ({}, {})",
        -llx * scale,
        ury * scale
    );
    eprintln!(
        "  => PDF point ({urx}, {ury}) maps to device ({}, {})",
        urx * scale - llx * scale,
        ury * scale - ury * scale
    );
    let pixel_w = ((urx - llx).abs() * scale).round() as u32;
    let pixel_h = ((ury - lly).abs() * scale).round() as u32;
    eprintln!("  Pixel dimensions: {pixel_w} x {pixel_h}");
    eprintln!("  render_region viewport: (0, 0, {pixel_w}, {pixel_h})");

    // Dump bounding boxes of first 20 fill/stroke elements
    let mut count = 0;
    for (i, elem) in display_list.elements().iter().enumerate() {
        if count >= 20 {
            break;
        }
        match elem {
            DisplayElement::Fill { path, params } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!(
                    "  [{i}] FILL color={:?} bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})",
                    params.color
                );
                count += 1;
            }
            DisplayElement::Stroke { path, params } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!(
                    "  [{i}] STROKE color={:?} lw={:.2} bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})",
                    params.color, params.line_width
                );
                count += 1;
            }
            DisplayElement::Clip { path, .. } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!("  [{i}] CLIP bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})");
                count += 1;
            }
            DisplayElement::Image { params, .. } => {
                eprintln!(
                    "  [{i}] IMAGE {}x{} ctm=[{:.1},{:.1},{:.1},{:.1},{:.1},{:.1}]",
                    params.width,
                    params.height,
                    params.ctm.a,
                    params.ctm.b,
                    params.ctm.c,
                    params.ctm.d,
                    params.ctm.tx,
                    params.ctm.ty
                );
                count += 1;
            }
            DisplayElement::InitClip => {
                eprintln!("  [{i}] INITCLIP");
            }
            DisplayElement::ErasePage => {
                eprintln!("  [{i}] ERASEPAGE");
            }
            _ => {}
        }
    }

    // === javaplatform.pdf ===
    eprintln!("\n=== javaplatform.pdf page 0 ===");
    let data2 = load_pdf("javaplatform.pdf");
    let doc2 = PdfDocument::from_bytes(&data2).unwrap();
    let info2 = doc2.page_info(0).unwrap();
    eprintln!("  MediaBox: {:?}", info2.media_box);
    eprintln!("  CropBox:  {:?}", info2.crop_box);
    eprintln!("  Rotate:   {}", info2.rotate);
    let (w2, h2) = doc2.page_size(0).unwrap();
    eprintln!("  page_size: {w2} x {h2} points");

    let contents2 = doc2.page_contents(0).unwrap();
    let preview_len2 = 500.min(contents2.len());
    let preview2 = String::from_utf8_lossy(&contents2[..preview_len2]);
    eprintln!("  Content stream first {preview_len2} bytes:\n---\n{preview2}\n---");

    let display_list2 = doc2.render_page(0, 72.0).unwrap();
    eprintln!("  Display list: {} elements", display_list2.len());

    let mut count2 = 0;
    for (i, elem) in display_list2.elements().iter().enumerate() {
        if count2 >= 20 {
            break;
        }
        match elem {
            DisplayElement::Fill { path, params } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!(
                    "  [{i}] FILL color={:?} bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})",
                    params.color
                );
                count2 += 1;
            }
            DisplayElement::Stroke { path, params } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!(
                    "  [{i}] STROKE color={:?} lw={:.2} bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})",
                    params.color, params.line_width
                );
                count2 += 1;
            }
            DisplayElement::Clip { path, .. } => {
                let (min_x, min_y, max_x, max_y) = path_bbox(&path.segments);
                eprintln!("  [{i}] CLIP bbox=({min_x:.1}, {min_y:.1}) - ({max_x:.1}, {max_y:.1})");
                count2 += 1;
            }
            DisplayElement::Image { params, .. } => {
                eprintln!(
                    "  [{i}] IMAGE {}x{} ctm=[{:.1},{:.1},{:.1},{:.1},{:.1},{:.1}]",
                    params.width,
                    params.height,
                    params.ctm.a,
                    params.ctm.b,
                    params.ctm.c,
                    params.ctm.d,
                    params.ctm.tx,
                    params.ctm.ty
                );
                count2 += 1;
            }
            _ => {}
        }
    }
}

fn path_bbox(segments: &[stet_fonts::geometry::PathSegment]) -> (f64, f64, f64, f64) {
    use stet_fonts::geometry::PathSegment;
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    for seg in segments {
        let points: Vec<(f64, f64)> = match seg {
            PathSegment::MoveTo(x, y) | PathSegment::LineTo(x, y) => vec![(*x, *y)],
            PathSegment::CurveTo {
                x1,
                y1,
                x2,
                y2,
                x3,
                y3,
            } => {
                vec![(*x1, *y1), (*x2, *y2), (*x3, *y3)]
            }
            PathSegment::ClosePath => vec![],
        };
        for (x, y) in points {
            min_x = min_x.min(x);
            min_y = min_y.min(y);
            max_x = max_x.max(x);
            max_y = max_y.max(y);
        }
    }
    (min_x, min_y, max_x, max_y)
}

#[test]
fn dump_display_list_stats() {
    use stet_graphics::display_list::DisplayElement;

    let data = load_pdf("hospital.pdf");
    let doc = PdfDocument::from_bytes(&data).unwrap();
    let dl = doc.render_page(0, 72.0).unwrap();

    let mut fills = 0u32;
    let mut strokes = 0u32;
    let mut clips = 0u32;
    let mut images = 0u32;
    let mut init_clips = 0u32;
    let mut erase_pages = 0u32;
    let mut white_fills = 0u32;
    let mut non_white_fills = 0u32;
    let mut y_min_all = f64::INFINITY;
    let mut y_max_all = f64::NEG_INFINITY;

    // Y buckets for non-white fills
    let mut y_buckets = [0u32; 7]; // 0-100, 100-200, ..., 600-700

    for elem in dl.elements() {
        match elem {
            DisplayElement::Fill { path, params } => {
                fills += 1;
                let is_white =
                    params.color.r > 0.99 && params.color.g > 0.99 && params.color.b > 0.99;
                if is_white {
                    white_fills += 1;
                } else {
                    non_white_fills += 1;
                    let (_, mny, _, mxy) = path_bbox(&path.segments);
                    y_min_all = y_min_all.min(mny);
                    y_max_all = y_max_all.max(mxy);
                    let cy = (mny + mxy) / 2.0;
                    let bucket = (cy / 100.0) as usize;
                    if bucket < 7 {
                        y_buckets[bucket] += 1;
                    }
                }
            }
            DisplayElement::Stroke { path, params } => {
                strokes += 1;
                let (_, mny, _, mxy) = path_bbox(&path.segments);
                y_min_all = y_min_all.min(mny);
                y_max_all = y_max_all.max(mxy);
            }
            DisplayElement::Clip { .. } => clips += 1,
            DisplayElement::Image { .. } => images += 1,
            DisplayElement::InitClip => init_clips += 1,
            DisplayElement::ErasePage => erase_pages += 1,
            _ => {}
        }
    }

    eprintln!("hospital.pdf display list stats:");
    eprintln!("  Total: {}", dl.len());
    eprintln!("  Fills: {fills} (white: {white_fills}, non-white: {non_white_fills})");
    eprintln!("  Strokes: {strokes}");
    eprintln!("  Clips: {clips}");
    eprintln!("  Images: {images}");
    eprintln!("  InitClip: {init_clips}, ErasePage: {erase_pages}");
    eprintln!("  Non-white Y range: [{y_min_all:.1}, {y_max_all:.1}]");
    eprintln!("  Non-white fills by Y bucket:");
    for (i, &count) in y_buckets.iter().enumerate() {
        eprintln!("    y={:>3}-{:>3}: {count}", i * 100, (i + 1) * 100);
    }

    // Show first 10 images
    eprintln!("\n  First 10 images:");
    let mut shown = 0;
    for (i, elem) in dl.elements().iter().enumerate() {
        if shown >= 10 {
            break;
        }
        if let DisplayElement::Image {
            params,
            sample_data,
        } = elem
        {
            eprintln!(
                "    [{i}] {}x{} cs={:?} data_len={} ctm=[{:.2},{:.2},{:.2},{:.2},{:.2},{:.2}] im=[{:.0},{:.0},{:.0},{:.0},{:.0},{:.0}]",
                params.width,
                params.height,
                params.color_space,
                sample_data.len(),
                params.ctm.a,
                params.ctm.b,
                params.ctm.c,
                params.ctm.d,
                params.ctm.tx,
                params.ctm.ty,
                params.image_matrix.a,
                params.image_matrix.b,
                params.image_matrix.c,
                params.image_matrix.d,
                params.image_matrix.tx,
                params.image_matrix.ty
            );
            shown += 1;
        }
    }

    // Show first 5 clips
    eprintln!("\n  First 10 clips:");
    let mut shown2 = 0;
    for (i, elem) in dl.elements().iter().enumerate() {
        if shown2 >= 10 {
            break;
        }
        if let DisplayElement::Clip { path, .. } = elem {
            let (mnx, mny, mxx, mxy) = path_bbox(&path.segments);
            eprintln!(
                "    [{i}] bbox=({mnx:.1},{mny:.1})-({mxx:.1},{mxy:.1}) segs={}",
                path.segments.len()
            );
            shown2 += 1;
        }
    }
}

/// Test against external PDFs if available (e.g., downloaded or from /tmp).
#[test]
fn parse_external_pdfs() {
    // Try any PDFs in /tmp
    let paths: Vec<_> = std::fs::read_dir("/tmp")
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "pdf"))
        .map(|e| e.path())
        .collect();

    let mut parsed = 0;
    let mut failed = 0;
    for path in &paths {
        if let Some(data) = load_pdf_abs(path.to_str().unwrap()) {
            match PdfDocument::from_bytes(&data) {
                Ok(doc) => {
                    assert!(doc.page_count() > 0 || doc.page_count() == 0);
                    parsed += 1;
                }
                Err(stet_pdf_reader::PdfError::Encrypted) => {
                    parsed += 1; // Expected failure for encrypted PDFs
                }
                Err(_e) => {
                    failed += 1;
                    eprintln!("  FAIL: {}: {_e}", path.display());
                }
            }
        }
    }
    if !paths.is_empty() {
        eprintln!(
            "External PDFs: {parsed} parsed, {failed} failed out of {} total",
            paths.len()
        );
    }
}
